version: "3"

services: 
    Engine:
        container_name: TSGE
        image: nginx:1.14.2-alpine
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./dist:/usr/share/nginx/html:ro